config/routes.rb
Rails.application.routes.draw do
  get 'home/landpage'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :regalos do
    collection do
      get 'show_details'
      get :confirmation
    end
  end

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}

  root 'regalos#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/regalo.rb
class Regalo < ActiveRecord::Base

  belongs_to :user
  mount_uploader :img_product, ImageProductUploader

  validates_processing_of :img_product
  validate :image_size_validation

  private
  def image_size_validation
    errors[:img_product] << "should be less than 800KB" if img_product.size > 0.8.megabytes
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :regalos

  mount_uploader :img_contact, ImgContactUploader

  attr_accessor :skip_password_validation
  attr_accessor :invite_code
  validate :invite_code_valid, :on => :create
  validates_processing_of :img_contact
  validate :image_size_validation

  private

  def password_required?
    return false if skip_password_validation
    super
  end

  def invite_code_valid

    if self.invite_code.casecmp("pipecami2502") != 0
      self.errors.add(:invite_code, "inválido. Intenta nuevamente o escríbeme a felipe.fabiop@gmail.com")
    end
  end

  def image_size_validation
    errors[:img_contact] << "should be less than 800KB" if img_contact.size > 0.8.megabytes
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    root_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def landpage
  end
end

app/controllers/regalos_controller.rb
class RegalosController < InheritedResources::Base

  def show_details
    @regalo = Regalo.find(params[:id_regalo])
    if @regalo.state == 1
      @user = User.find(@regalo.user_id)
    end
  end

  private

    def regalo_params
      params.require(:regalo).permit(:name, :description, :price_min, :price_max, :link, :img_product, :state)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  skip_before_filter :verify_authenticity_token, :only => :create
# before_action :configure_account_update_params, only: [:update]
  respond_to :json, :js

  # GET /resource/sign_up
  def new
    @regalo = Regalo.find(params[:id_regalo])
    super
  end

  # POST /resource
  def create
    build_resource(sign_up_params)
    @regalo = Regalo.find(params[:regalo])
    resource.invite_code = params[:user][:invite_code]
    resource.skip_password_validation = true
    if resource.save
      @regalo.user = resource
      @regalo.state = 1
      @regalo.save
      set_flash_message! :notice, :signed_up
      sign_up(resource_name, resource)

      render "regalos/confirmation"
      # respond_to do |format|
      #   format.js {redirect_to controller: '/regalos', action: 'confirmation', user: resource.id, regalo: @regalo.id, format: :js}
      # end
      #respond_with resource, location: after_sign_up_path_for(resource)
    else
      resource.invite_code = ""
      @error_message = resource.errors.full_messages
      render "users/registrations/new"
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:invite_code, :name, :img_contact])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/regalos_helper.rb
module RegalosHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/

    %title Lista de Regalos Matrimonio Felipe & Hazbel
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Lemonada", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Arima+Madurai", :rel => "stylesheet"}/

    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet", integrity: "sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN", crossorigin: "anonymous"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    =# stylesheet_link_tag    'regalos', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'regalos/header'
    = yield

app/views/regalos/_confirmation.html.haml
#modal2.modal.modal2
  .modal-content
    %h4.center
      Regalo reservado!
    %p
      #{resource.name},
      ya eres parte de nuestra lista de regalos y parte de nuestro hogar,
      seguro tu regalo nos será de mucha ayuda.
      %br
      Te recordamos que puedes comprarlo en este link, o en cualquier
      otro lugar que te acomode más:

    %span Regalo: #{@regalo.name}
    %br
    %a{href: "#{@regalo.link}", target: "_blank"}
      #{@regalo.link}

    %p
      Si gustas puedes venir a entregarnos tu regalo personalmente o
      enviarlo a: Lautaro #1341, Barrancas, San Antonio (casa de la Cami,
      nuestra casa estamos arreglando cosas aún)
    %p
      Cualquier consulta con los novios (+56985491510 Felipe/+65994686375 Cami)
    %p
      Atte.
    %p.center
      %b
        Felipe & Cami <3

  .modal-footer
    %a.modal-action.modal-close.waves-effect.waves-green.btn-flat{href: root_url}
      Salir

app/views/regalos/_form.html.erb
<%= form_for(@regalo) do |f| %>
  <% if @regalo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@regalo.errors.count, "error") %> prohibited this regalo from being saved:</h2>

      <ul>
      <% @regalo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_min %><br>
    <%= f.number_field :price_min %>
  </div>
  <div class="field">
    <%= f.label :price_max %><br>
    <%= f.number_field :price_max %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :img_product %><br>
    <%= f.text_field :img_product %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.number_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regalos/_header.haml
.navbar-fixed
  %nav
    .nav-wrapper.u-green
      %a.brand-logo.lemonada{:href => root_url} ¡Bienvenidos!
      %a.button-collapse{"data-activates" => "mobile-app", :href => "#"}
        %i.material-icons menu
      %ul.right.hide-on-med-and-down
        %li

        %li
          %a.waves-effect.waves-light.btn-large.btn-gift{href: "#regalos"}
            Regálanos!

      %ul#mobile-app.side-nav.u-green
        %li
          %a.waves-effect.waves-light.btn-gift.btn{href: "#regalos"}
            Regálanos!

app/views/regalos/_show.html.haml
#modal1.modal
  .modal-content
    %p#notice= notice
    .row
      .col.s12.m6
        = image_tag "#{@regalo.img_product.url.present? ? @regalo.img_product.url : 'http://placehold.it/250x236'}", class: "img-responsive", width: "100%"
      .col.s12.m6
        %h5
          = @regalo.name
        -if @regalo.description.present?
          %p
            %strong Description:
            = @regalo.description

        - if !@regalo.price_min.present?
          %p
            = number_to_currency(@regalo.price_max, precision: 0, separator: ".", unit: "$", format: "%u %n")
        - else
          %p
            = "#{number_to_currency(@regalo.price_min, precision: 0, separator: ".", unit: "$", format: "%u %n")} - #{number_to_currency(@regalo.price_max, precision: 0, separator: ".", unit: "$", format: "%u %n")}"

        -if @regalo.state == 1
          .chip
            = image_tag @user.img_contact.thumb.url
            = @user.name

        %br
        %br

        %p
          %strong Link:
          = link_to "#{@regalo.link}", @regalo.link, target: "_blank"
        %small
          *Este regalo lo vimos aquí, aunque puedes buscar
          otros lugares donde lo vendan.
    .row
      .col.s12.m12

  .modal-footer
    %a.modal-action.modal-close.waves-effect.waves-green.btn-flat{:href => "#!"} Agree

-#
-#%p#notice= notice
-#%p
-#  %strong Name:
-#  = @regalo.name
-#%p
-#  %strong Description:
-#  = @regalo.description
-#%p
-#  %strong Price-min:
-#  = @regalo.price_min
-#%p
-#  %strong Price-max:
-#  = @regalo.price_max
-#%p
-#  %strong Link:
-#  = @regalo.link
-#%p
-#  %strong Img-product:
-#  = @regalo.img_product
-#%p
-#  %strong State:
-#  = @regalo.state
-#= link_to 'Back', regalos_path

app/views/regalos/edit.html.erb
<h1>Editing Regalo</h1>

<%= render 'form' %>

<%= link_to 'Show', @regalo %> |
<%= link_to 'Back', regalos_path %>

app/views/regalos/index.html.haml
.parallax-container
  .opacity-wrap
    .section.no-pad-bot
      .container.mr-top-ten.center.white-text
        %h4.header.center MATRIMONIO
        %h1.header.center.lemonada Felipe y Camila
        %hr.white-text{:width => "40%"}
        %h5.center.pd-top
          25 de Febrero de 2017
        %i.fa.fa-heart-o.center.fa-2x
        %i.fa.fa-heart-o.center.fa-2x

.section.u-versiculo.darken-1
  .valign-wrapper{style: "height: 200px;"}
    .container.black-text
      %h5.valign.center.light.arima
        %i.fa.fa-angle-double-left
        Que tu amor inagotable nos rodee, Señor, porque solo en ti está nuestra esperanza.
        %i.fa.fa-angle-double-right
      %h6.right.pd-right
        Salmos 33:22

.section.u-bride.u-green-light.pd-top
  .container
    .row.center.white-text
      %h4.header.white-text
        NUESTRA BODA
      %hr{:width => "25%"}
      -#%i.fa.fa-heart-o.center.fa-lg
    .row.pd-top-2.white-text
      .col.m4.s12.offset-m1
        = image_tag "photo_juntos.jpg", class: "u-bride-img"
      .col.m6.offset-m1
        .row.pd-top
          .col.m2.s12
            = image_tag "big-church.png", class: "u-bride-icon"
          .col.m8
            %p.u-bride-paragraph
              Nuestra ceremonia será en la Iglesia Metodista Pentecostal. Ubicada en Libertad #193, San Antonio.
        .row.pd-top
          .col.m2.s12
            = image_tag "gift.png", class: "u-bride-icon"
          .col.m8
            %p.u-bride-paragraph
              Hemos creado esta web para mostrales los regalos más lindos que hemos visto en diferentes partes (no nos amarramos a una tienda)
        .row.pd-top
          .col.m2.s12
            = image_tag "user (2).png", class: "u-bride-icon"
          .col.m8
            %p.u-bride-paragraph
              Las mejores cosas de la vida merecen ser compartidas, prepárate para celebrar con nosotros!


#regalos.section.scrollspy
  -#.row{style: "background: url(#{image_url("bg-pink-hearts.jpg")}) left top repeat;"}
  #show_details
  .row.white.pd-top-two.center
    .col.m12
      %p#notice= notice
      %h4.header.center
        LISTA DE REGALOS
      %hr{:width => "25%"}
      %i.fa.fa-gift.center.fa-2x
      .container
        %br
        %p.center
          Estos regalos los hemos escogido cuidadosamente
          para que sean parte de nuestro hogar. Se parte tú también :D
      %br

    .row.left
      .container
        - @regalos.order("state DESC").each do |regalo|
          .col.s12.m6
            .card.card-gift.horizontal.hoverable.white
              .card-image
                %a{href: "#{regalo.link}", target: "_blank"}
                  = image_tag "#{regalo.img_product.url.present? ? regalo.img_product.url : 'http://placehold.it/250x236'}", class: "", height: "220"
              .card-content.mg-left
                .title-regalo
                  .light
                    = link_to regalo.name, regalo.link, target: "_blank"

                .price-text.light
                  - if !regalo.price_min.present?
                    %p
                      Precio:
                      = number_to_currency(regalo.price_max, precision: 0, separator: ".", unit: "$", format: "%u %n")
                  - else
                    %p
                      Precio:
                      = "#{number_to_currency(regalo.price_min, precision: 0, separator: ".", unit: "$", format: "%u %n")} - #{number_to_currency(regalo.price_max, precision: 0, separator: ".", unit: "$", format: "%u %n")}"


                -if regalo.state == 1
                  -if regalo.user_id.present?
                    - user = User.find(regalo.user_id)
                    .chip.truncate.pd-top
                      = image_tag user.img_contact.thumb.url
                      = user.name
                -else
                  .chip.green.darken-1.pd-top
                    .white-text
                      Disponible

                .pd-top-2
                  = link_to 'Regalar!', {:controller => "users/registrations",:action => 'new', :id_regalo => regalo.id}, {:class => 'btn waves-effect waves-light teal', :method => 'get', remote: true, form: { "data-type" => "script" }}

app/views/regalos/new.html.erb
<h1>New Regalo</h1>

<%= render 'form' %>

<%= link_to 'Back', regalos_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>